### ISSUE TITLE
Lazy-load component in angular 17

### ISSUE THREAD

**Issue by ABC-ACL** [MTobisch/ngx-dynamic-hooks#41]
Hello,

Thanks for the great library.

I'm having trouble lazy-loading components, I tried it like this:
```
const componentParsers: Array<HookParserEntry> = [
    { component: {
         importPromise: () => import('.../test.component'),
         importName: "TestComponent"
  },
  selector: "app-test"
},
```

I also tried "import('.../test.component').then(mod => mod.TestComponent)", but doesnt' work either.

What I'm I doing wrong?

**Comment by MTobisch** [comment]
Hey there!

Is it possible that you have too many dots in the file path `'.../test.component'`? It the component is in the same directory, you would use one dot and if its in the parent directory, you'd use two dots. I don't think three dots are a thing?

**Comment by ABC-ACL** [comment]
Sorry, I edited out the path (and the component name) for the example. That is not the problem.

The error I get when I import a component that way is (from the chrome console):

`polyfills.js:1 ERROR TypeError: m.hasOwnProperty is not a function
    at ngx-dynamic-hooks.mjs:2773:29
    at v.invoke (polyfills.js:1:8305)
    at Object.onInvoke (core.mjs:14695:33)
    at v.invoke (polyfills.js:1:8245)
    at h.run (polyfills.js:1:3648)
    at polyfills.js:2:562
    at v.invokeTask (polyfills.js:1:8933)
    at core.mjs:14369:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14369:36)
    at v.invokeTask (polyfills.js:1:8854)`

**Comment by MTobisch** [comment]
So, it seems this is the code that triggers the error in the library:

```ts
componentConfig.importPromise().then((m) => {
    const importName = componentConfig.importName;
    const compClass = m.hasOwnProperty(importName) ? m[importName] : m['default'];
});
```

As you can see, there's nothing overly complex going on here, it just executes the import fn that is provided and then uses `hasOwnProperty` with `importName` to check if a component with that name exists in the loaded module to retrieve it. 

Its weird that it doesn't work for you as that code even if used outside the library works for me in Angular alone. I wonder if it might have something to do with a particular browser, Angular version & library version combination.

**Comment by ABC-ACL** [comment]
I made the simplest example possible, published here: (https://github.com/ABC-ACL/hookTest

The moment I change to the importPromise I get that error in the browser, and this one in the ng serve terminal:

`ReferenceError: document is not defined
    at PlatformBrowserService.getNgVersion (c:/Users/ABC/git/hookTest/node_modules/ngx-dynamic-hooks/fesm2020/ngx-dynamic-hooks.mjs:3323:5)
    at ComponentCreator.loadComponentClass (c:/Users/ABC/git/hookTest/node_modules/ngx-dynamic-hooks/fesm2020/ngx-dynamic-hooks.mjs:2766:39)
    at eval (c:/Users/ABC/git/hookTest/node_modules/ngx-dynamic-hooks/fesm2020/ngx-dynamic-hooks.mjs:2562:33)
    at doInnerSub (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/operators/mergeInternals.js:19:19)
    at outerNext (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/operators/mergeInternals.js:14:57)
    at OperatorSubscriber.OperatorSubscriber._next (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/operators/OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/Subscriber.js:31:18)
    at _Observable.eval (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/observable/innerFrom.js:51:24)
    at _Observable._trySubscribe (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/Observable.js:37:25)
    at eval (c:/Users/ABC/git/hookTest/node_modules/rxjs/dist/esm/internal/Observable.js:31:30)`

**Comment by MTobisch** [comment]
Hi again!

Can you test the new [v.2.1.1](https://www.npmjs.com/package/ngx-dynamic-hooks) and report if the errors are still occurring?

I hadn't tested the library yet with Angular 17, and it seems many of the problems occur when used in combination with the new and seamless integration of SSR, which your example repo also uses. Hence the errors that `document is not defined`. When server-rendering, there is indeed no `document` global var. Regarding the other error, `m.hasOwnProperty is not a function`, I'm honestly not sure what changed there. Perhaps its a consequence of an SSR error, perhaps they changed the polyfill.

Either way, I've addressed them both with the new version. Hopefully, it works for you.

As a side note, the library was initially developed at a time when SSR (then called Angular Universal) was a separate package and not as mature as SSR is now. As such, the library wasn't ever really designed to work specifically with it. I'm honestly pleased to see that it does, generally.

**Comment by ABC-ACL** [comment]
Seems to work great  now, with ssr and hydration.
Many thanks!
